## Linear Regression with PyTorch

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

The *learning* part of linear regression is to figure out a set of weights `w11, w12,... w23, b1 & b2` by looking at the training data, to make accurate predictions for new data (i.e. to predict the yields for apples and oranges in a new region using the average temperature, rainfall and humidity). This is done by adjusting the weights slightly many times to make better predictions, using an optimization technique called *gradient descent*.

In [1]:
# Uncomment the command below if Numpy or PyTorch is not installed
# !conda install numpy pytorch cpuonly -c pytorch -y

In [2]:
import numpy as np
import torch

## Training data

The training data can be represented using 2 matrices: `inputs` and `targets`, each with one row per observation, and one column per variable.

In [21]:
# Input (temperature, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]],dtype='float32')

In [22]:
#Target (apple, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]],dtype='float32')

In [23]:
#Convert inputs and targets into tensor
train_data = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [24]:
#inputs tensor
print(inputs)

[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]


In [25]:
#targets tensor
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear regression model from scratch

The weights and biases (`w11, w12,... w23, b1 & b2`) can also be represented as matrices, initialized as random values. The first row of `w` and the first element of `b` are used to predict the first target variable i.e. yield of apples, and similarly the second for oranges.

In [26]:
#create random weights and biases
weights = torch.randn(2, 3, requires_grad=True)
biases = torch.randn(2, requires_grad=True)

`torch.randn` creates a tensor with the given shape, with elements picked randomly from a [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) with mean 0 and standard deviation 1.

Our *model* is simply a function that performs a matrix multiplication of the `inputs` and the weights `w` (transposed) and adds the bias `b` (replicated for each observation).

In [27]:
#weights
print(weights)

tensor([[ 0.1217, -0.0290, -0.4326],
        [-0.8604, -0.0011,  1.0259]], requires_grad=True)


In [28]:
#biases
print(biases)

tensor([ 0.1467, -0.2048], requires_grad=True)


In [30]:
#define model
def model(train_data, weights, biases):
    return train_data @ weights.t() + biases   

`@` represents matrix multiplication in PyTorch, and the `.t` method returns the transpose of a tensor.

The matrix obtained by passing the input data into the model is a set of predictions for the target variables.

In [32]:
#Generate predictions
predictions = model(train_data, weights, biases)
print(predictions)

tensor([[-11.5172, -18.9721],
        [-19.0208, -12.9379],
        [-18.2463, -15.7024],
        [ -4.6977, -50.0523],
        [-24.5247,  12.1372]], grad_fn=<AddBackward0>)


#### Let's compare the predictions of our model with the actual targets.

In [33]:
#compare with targets
print(target)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


#### You can see that there's a huge difference between the predictions of our model, and the actual values of the target variables. Obviously, this is because we've initialized our model with random weights and biases, and we can't expect it to *just work*.