# torch.Tensor
 A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

In [1]:
import torch

## There are a few main ways to create a tensor, depending on your use case.

1. To create a tensor with pre-existing data, use torch.tensor().

2. To create a tensor with specific size, use torch.* tensor creation ops.

3. To create a tensor with the same size (and similar types) as another tensor, use torch.*_like tensor creation ops.

4. To create a tensor with similar type but different size as another tensor, use tensor.new_* creation ops.

### Function 1 : torch.tensor

In [7]:
t1 = torch.tensor([[1,23,-4],[9,4.5,0]])
print(t1.dtype)
print(t1)

torch.float32
tensor([[ 1.0000, 23.0000, -4.0000],
        [ 9.0000,  4.5000,  0.0000]])


### Function 3 : torch.*_like 

In [14]:
#(a) torch.zeros_like()
input = torch.empty(2,3)
t = torch.zeros_like(input)
t

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
#(b) torch.ones_like()
input = torch.empty(2,4)
t = torch.ones_like(input)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
#(c) torch.empty_like()
t = torch.empty_like(t1)
t

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
#(d) torch.rand_like()
input = torch.empty(3,2)
t = torch.rand_like(input)
t

tensor([[0.8095, 0.0220],
        [0.8246, 0.6129],
        [0.7703, 0.2741]])

In [20]:
#(e) torch.full_like()
input = torch.empty(5,4)
t = torch.full_like(input,fill_value=4.5)
t

tensor([[4.5000, 4.5000, 4.5000, 4.5000],
        [4.5000, 4.5000, 4.5000, 4.5000],
        [4.5000, 4.5000, 4.5000, 4.5000],
        [4.5000, 4.5000, 4.5000, 4.5000],
        [4.5000, 4.5000, 4.5000, 4.5000]])

In [27]:
#(f) torch.randint_like()
t = torch.randint_like(torch.empty(3,2),low=-100,high=100)
t

tensor([[-95., -37.],
        [  7., -47.],
        [ 52., -47.]])

In [28]:
#(g) torch.randn_like()
t = torch.randn_like(torch.empty(3,4))
t

tensor([[ 1.1549,  0.5568,  0.1568,  0.2870],
        [ 2.9359, -0.5719,  0.6126,  0.7819],
        [ 0.9602, -0.5646, -0.3428, -0.4457]])