# PyTorch Basics: Tensors & Gradients

In [3]:
# Uncomment the command below if PyTorch is not installed
# !conda install pytorch cpuonly -c pytorch -y

## Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number:

In [4]:
import torch

In [8]:
#Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [7]:
t1.dtype

torch.float32

In [10]:
#Vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [11]:
t2.dtype

torch.float32

In [13]:
#Matrix
t3 = torch.tensor([[1,2],
                   [3,4],
                   [5,6.]])
t3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [14]:
t3.dtype

torch.float32

In [16]:
#3-dimensional array
t4 = torch.tensor([[[1,2,3],
                    [3,4,5]],
                   [[5,6,7],
                    [7,8,9]],
                   [[9,10,11],
                    [11,12.,13]]
                  ])
t4

tensor([[[ 1.,  2.,  3.],
         [ 3.,  4.,  5.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])

In [17]:
t4.dtype

torch.float32

Tensors can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of a tensor.

In [18]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [20]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [21]:
print(t3)
t3.shape

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


torch.Size([3, 2])

In [22]:
print(t4)
t4.shape

tensor([[[ 1.,  2.,  3.],
         [ 3.,  4.,  5.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[ 9., 10., 11.],
         [11., 12., 13.]]])


torch.Size([3, 2, 3])

## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look an example:

In [32]:
#create tensors
x = torch.tensor(5.)
y = torch.tensor(6.,requires_grad=True)
z = torch.tensor(7.,requires_grad=True)
x, y, z

(tensor(5.), tensor(6., requires_grad=True), tensor(7., requires_grad=True))

We've created 3 tensors `x`, `y` and `y`, all numbers.
Let's create a new tensor `t` by combining these tensors:

In [33]:
t = y * x + z
t

tensor(37., grad_fn=<AddBackward0>)

As expected, `t` is a tensor with the value `6 * 5 + 7 = 37`. What makes PyTorch special is that we can automatically compute the derivative of `t` w.r.t. the tensors that have `requires_grad` set to `True` i.e. y and z. To compute the derivatives, we can call the `.backward` method on our result `t`.

In [34]:
#Compute derivatves
t.backward()

The derivates of `t` w.r.t the input tensors are stored in the `.grad` property of the respective tensors.

In [35]:
print('dt/dx : ',x.grad)
print('dt/dy : ',y.grad)
print('dt/dz : ',z.grad)

dt/dx :  None
dt/dy :  tensor(5.)
dt/dz :  tensor(1.)


## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular open source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries:

* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing
* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis

Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.

In [37]:
import numpy as np

arr = np.array([[1,2],[3,4]]) 
arr

array([[1, 2],
       [3, 4]])

We can convert a Numpy array to a PyTorch tensor using `torch.from_numpy`.

In [38]:
t = torch.from_numpy(arr)
t

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Let's verify that the numpy array and torch tensor have similar data types.

In [39]:
arr.dtype, t.dtype

(dtype('int32'), torch.int32)

We can convert a PyTorch tensor to a Numpy array using the `.numpy` method of a tensor.

In [40]:
#Convert a torch tensor to numpy array
x = t.numpy()
x

array([[1, 2],
       [3, 4]])

The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

## Further Reading
[Tensor Operations](https://pytorch.org/docs/stable/tensors.html)

[PyTorch Tutorial for Deep Learning Researchers](https://github.com/yunjey/pytorch-tutorial) by Yunjey Choi

[FastAI development notebooks](https://github.com/fastai/fastai_docs/tree/master/dev_nb) by Jeremy Howard